name: Run App Store Rank Scraper (Daily)

on:
  schedule:
    - cron: "0 6 * * *"   # runs every day at 06:00 UTC
  workflow_dispatch:      # allows manual run

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python app_rank_scraper.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add AppRanks.csv
          git commit -m "Daily data update $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
