name: Run App Store Rank Scraper (Daily)

on:
  schedule:
    - cron: "0 7 * * *"  # 08:00 Berlin time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run scraper
        run: python app_rank_scraper.py

      - name: Upload CSV to Google Drive
        env:
          GDRIVE_SERVICE_KEY: ${{ secrets.GDRIVE_SERVICE_KEY }}
        run: |
          echo "$GDRIVE_SERVICE_KEY" > service.json

          python << 'EOF'
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

SCOPES = ['https://www.googleapis.com/auth/drive.file']

creds = service_account.Credentials.from_service_account_file(
    "service.json",
    scopes=SCOPES
)

drive_service = build('drive', 'v3', credentials=creds)

file_metadata = {"name": "AppRanks.csv"}
media = MediaFileUpload("AppRanks.csv", mimetype="text/csv")

file = drive_service.files().create(
    body=file_metadata,
    media_body=media,
    fields="id"
).execute()

print("✅ Uploaded AppRanks.csv to Google Drive")
EOF

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add AppRanks.csv
          git commit -m "Auto update $(date -u)" || echo "No changes to commit"
          git push
