      - name: Upload CSV to Google Drive
        env:
          GDRIVE_SERVICE_KEY: ${{ secrets.GDRIVE_SERVICE_KEY }}
        run: |
          echo "$GDRIVE_SERVICE_KEY" > service.json
          python <<'EOF'
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

# authenticate using service account
gauth = GoogleAuth()
gauth.ServiceAuth()
drive = GoogleDrive(gauth)

file = drive.CreateFile({'title': 'AppRanks.csv'})
file.SetContentFile('AppRanks.csv')
file.Upload()
print("✅ Uploaded AppRanks.csv to Google Drive")
EOF
