name: Run App Store Rank Scraper (Daily)

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 07:00 UTC (08:00 Berlin)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python app_rank_scraper.py

      - name: Install Google Drive uploader
        run: pip install pydrive2

      - name: Upload CSV to Google Drive
        env:
          GDRIVE_SERVICE_KEY: ${{ secrets.GDRIVE_SERVICE_KEY }}
        run: |
          # Write the service-account JSON from the secret to a file
          echo "$GDRIVE_SERVICE_KEY" > service.json

          # Use PyDrive2 with explicit service-config settings
          python <<'EOF'
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          # Configure PyDrive2 to use the service account key we just wrote
          gauth = GoogleAuth()
          gauth.settings['client_config_backend'] = 'service'
          gauth.settings['service_config'] = {'client_json_file_path': 'service.json'}
          gauth.ServiceAuth()

          drive = GoogleDrive(gauth)

          # Upload or overwrite AppRanks.csv
          file = drive.CreateFile({'title': 'AppRanks.csv'})
          file.SetContentFile('AppRanks.csv')
          file.Upload()
          print("✅ Uploaded AppRanks.csv to Google Drive")
          EOF

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add AppRanks.csv
          git commit -m "Auto update $(date -u)" || echo "No changes to commit"
          git push
